version: "3.9"

services:
  1_pure_ubuntu_jammy:
    # network_mode: "host"        
    platform: linux/amd64
    build: 
      context: ./basement/
      dockerfile: ./1_pure_ubuntu_jammy
    image: yingshaoxo/ubuntu_ssh_server_for_the_stupid_apple_macos_m1_system_1
    restart: unless-stopped
  2_ssh_ubuntu:
    depends_on:
    - 1_pure_ubuntu_jammy
    # network_mode: "host"        
    platform: linux/amd64
    build: 
      context: ./basement/
      dockerfile: ./2_ssh_ubuntu
    image: yingshaoxo/ubuntu_ssh_server_for_the_stupid_apple_macos_m1_system
    ports:
      - "2222:22"
    environment:
      - ssh_root_password=yingshaoxo
    volumes:
      - "~/ubuntu_docker:/root"
    restart: unless-stopped